name: Statswalespy Tests

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: get-data-action
        uses: ./.github/actions/test-get-data
